In [1]:
import numpy as np
import pandas as pd

In [2]:
index_val= [('cse',2019),('cse', 2020),('cse',2021),('cse', 2022),('ece', 2019),('ece',2020),('ece',2021),('ece',2022)]

In [3]:
a= pd.Series([1,2,3,4,5,6,7,8], index= index_val)

In [4]:
a
#Multi index series

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [5]:
a[('cse', 2022)]

np.int64(4)

In [7]:
multiindex= pd.MultiIndex.from_tuples(index_val)

In [8]:
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [9]:
multiindex= pd.MultiIndex.from_product([['ece','cse'],[2019,2020,2021,2022]])

In [36]:
multiindex

MultiIndex([('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022),
            ('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022)],
           )

In [14]:
multiSeries= pd.Series([1,2,3,4,5,6,7,8], index= multiindex)

In [15]:
multiSeries

ece  2019    1
     2020    2
     2021    3
     2022    4
cse  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [16]:
multiSeries['cse']

2019    5
2020    6
2021    7
2022    8
dtype: int64

In [17]:
s= multiSeries

In [21]:
a = s.unstack()

In [22]:
s

ece  2019    1
     2020    2
     2021    3
     2022    4
cse  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [23]:
a

     2019  2020  2021  2022
cse     5     6     7     8
ece     1     2     3     4

In [24]:
a.stack()

cse  2019    5
     2020    6
     2021    7
     2022    8
ece  2019    1
     2020    2
     2021    3
     2022    4
dtype: int64

In [25]:
branch_df1= pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16]
    ],
    index= multiindex,
    columns= ['avg_package' , 'students']
)

In [26]:
branch_df1

          avg_package  students
ece 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
cse 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [29]:
branch_df1.loc['cse']

      avg_package  students
2019            9        10
2020           11        12
2021           13        14
2022           15        16

In [30]:
branch_df2= pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0]
    ],
    index= [2019,2020,2021,2022],
    columns= pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [32]:
branch_df2['delhi']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [34]:
branch_df2['delhi']['avg_package']

2019    1
2020    3
2021    5
2022    7
Name: avg_package, dtype: int64

In [40]:
branch_df3= pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index= multiindex,
    columns= pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
ece 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
cse 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [41]:
branch_df1

          avg_package  students
ece 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
cse 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [42]:
branch_df1.unstack()

    avg_package                students
           2019 2020 2021 2022     2019 2020 2021 2022
cse           9   11   13   15       10   12   14   16
ece           1    3    5    7        2    4    6    8

In [43]:
branch_df1.unstack().unstack()

avg_package  2019  cse     9
                   ece     1
             2020  cse    11
                   ece     3
             2021  cse    13
                   ece     5
             2022  cse    15
                   ece     7
students     2019  cse    10
                   ece     2
             2020  cse    12
                   ece     4
             2021  cse    14
                   ece     6
             2022  cse    16
                   ece     8
dtype: int64

In [47]:
branch_df1.stack()

ece  2019  avg_package     1
           students        2
     2020  avg_package     3
           students        4
     2021  avg_package     5
           students        6
     2022  avg_package     7
           students        8
cse  2019  avg_package     9
           students       10
     2020  avg_package    11
           students       12
     2021  avg_package    13
           students       14
     2022  avg_package    15
           students       16
dtype: int64

In [49]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
ece 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
cse 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [50]:
branch_df3.head()

               delhi               mumbai
         avg_package students avg_package students
ece 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
cse 2019           9       10           0        0

In [51]:
branch_df3.shape

(8, 4)

In [52]:
branch_df3.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8 entries, ('ece', np.int64(2019)) to ('cse', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int64
 1   (delhi, students)      8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 632.0+ bytes

In [53]:
branch_df3.head(2)

               delhi               mumbai
         avg_package students avg_package students
ece 2019           1        2           0        0
    2020           3        4           0        0

In [54]:
branch_df3.duplicated()

ece  2019    False
     2020    False
     2021    False
     2022    False
cse  2019    False
     2020    False
     2021    False
     2022    False
dtype: bool

In [55]:
branch_df3.isnull()

               delhi               mumbai
         avg_package students avg_package students
ece 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False
cse 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False

In [57]:
branch_df3.loc['cse']

           delhi               mumbai
     avg_package students avg_package students
2019           9       10           0        0
2020          11       12           0        0
2021          13       14           0        0
2022          15       16           0        0

In [65]:
branch_df3.loc[('cse',2019)]

delhi   avg_package     9
        students       10
mumbai  avg_package     0
        students        0
Name: (cse, 2019), dtype: int64

In [61]:
branch_df3.iloc[0:5:2]

               delhi               mumbai
         avg_package students avg_package students
ece 2019           1        2           0        0
    2021           5        6           0        0
cse 2019           9       10           0        0

In [69]:
branch_df3['delhi']

          avg_package  students
ece 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
cse 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [70]:
branch_df3.sort_index(ascending=False)

               delhi               mumbai
         avg_package students avg_package students
ece 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0
cse 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0

In [72]:
branch_df3.sort_index(ascending=[False,True])

               delhi               mumbai
         avg_package students avg_package students
ece 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
cse 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [73]:
branch_df3.sort_index(level=1, ascending=[False])

               delhi               mumbai
         avg_package students avg_package students
ece 2022           7        8           0        0
cse 2022          15       16           0        0
ece 2021           5        6           0        0
cse 2021          13       14           0        0
ece 2020           3        4           0        0
cse 2020          11       12           0        0
ece 2019           1        2           0        0
cse 2019           9       10           0        0

In [74]:
branch_df3.transpose()

                    ece                 cse
                   2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_package    1    3    5    7    9   11   13   15
       students       2    4    6    8   10   12   14   16
mumbai avg_package    0    0    0    0    0    0    0    0
       students       0    0    0    0    0    0    0    0

In [75]:
branch_df3.swaplevel()

               delhi               mumbai
         avg_package students avg_package students
2019 ece           1        2           0        0
2020 ece           3        4           0        0
2021 ece           5        6           0        0
2022 ece           7        8           0        0
2019 cse           9       10           0        0
2020 cse          11       12           0        0
2021 cse          13       14           0        0
2022 cse          15       16           0        0

In [77]:
pd.DataFrame({'cse':[100], 'ece':[120], 'mech':[80]})

   cse  ece  mech
0  100  120    80

In [78]:
pd.DataFrame({'cse':[100], 'ece':[120], 'mech':[80]}).melt()

  variable  value
0      cse    100
1      ece    120
2     mech     80

In [79]:
pd.DataFrame({'cse':[100], 'ece':[120], 'mech':[80]}).melt(var_name= 'Branch', value_name= 'num_students')

  Branch  num_students
0    cse           100
1    ece           120
2   mech            80

In [81]:
pd.DataFrame(
    {
        'Branch' : ['cse','ece','mech'],
        '2020' : [100,150, 70],
        '2021' : [110,110, 30],
        '2022' : [120,120, 40]
    }
)
#Wide format

  Branch  2020  2021  2022
0    cse   100   110   120
1    ece   150   110   120
2   mech    70    30    40

In [82]:
pd.DataFrame(
    {
        'Branch' : ['cse','ece','mech'],
        '2020' : [100,150, 70],
        '2021' : [110,110, 30],
        '2022' : [120,120, 40]
    }
).melt()

   variable value
0    Branch   cse
1    Branch   ece
2    Branch  mech
3      2020   100
4      2020   150
5      2020    70
6      2021   110
7      2021   110
8      2021    30
9      2022   120
10     2022   120
11     2022    40

In [83]:
pd.DataFrame(
    {
        'Branch' : ['cse','ece','mech'],
        '2020' : [100,150, 70],
        '2021' : [110,110, 30],
        '2022' : [120,120, 40]
    }
).melt(id_vars= ['Branch'])

  Branch variable  value
0    cse     2020    100
1    ece     2020    150
2   mech     2020     70
3    cse     2021    110
4    ece     2021    110
5   mech     2021     30
6    cse     2022    120
7    ece     2022    120
8   mech     2022     40

In [84]:
pd.DataFrame(
    {
        'Branch' : ['cse','ece','mech'],
        '2020' : [100,150, 70],
        '2021' : [110,110, 30],
        '2022' : [120,120, 40]
    }
).melt(id_vars= ['Branch'], var_name= 'year', value_name= 'students')

  Branch  year  students
0    cse  2020       100
1    ece  2020       150
2   mech  2020        70
3    cse  2021       110
4    ece  2021       110
5   mech  2021        30
6    cse  2022       120
7    ece  2022       120
8   mech  2022        40

In [85]:
confirmed= pd.read_csv("Datasets/time_series_covid19_confirmed_global.csv")

In [86]:
death= pd.read_csv("Datasets/time_series_covid19_deaths_global.csv")

In [87]:
death

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5708,5708,5708,5708,5708,5708,5708,5708,5708,5708
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2159,2159,2159,2159,2159,2159,2159,2159,2159,2159
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,4019,4019,4022,4022,4023,4023,4024,4024,4024,4024
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5637,5637,5637,5637,5637,5637,5637,5637,5637,5637

In [88]:
confirmed

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,703228,703228,703228,703228,703228,703228,703228,703228,703228,703228
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,535
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,11945,11945,11945,11945,11945,11945,11945,11945,11945,11945
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,334021,334021,334066,334108,334196,334294,334425,334425,334629,334661
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,259981,259981,259981,259981,259981,259981,259981,259981,259981,259981

In [89]:
death.shape

(289, 1081)

In [90]:
confirmed.shape

(289, 1081)

In [93]:
death = death.melt(id_vars=['Province/State','Country/Region','Lat','Long'], var_name='date', value_name= 'num_deaths')

In [94]:
confirmed = confirmed.melt(id_vars=['Province/State','Country/Region','Lat','Long'], var_name='date', value_name= 'num_deaths')

In [95]:
death

,Province/State,Country/Region,Lat,Long,date,num_deaths
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,5637

In [96]:
confirmed

,Province/State,Country/Region,Lat,Long,date,num_deaths
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981

In [98]:
confirmed.merge(death, on=['Province/State','Country/Region','Lat','Long', 'date'])

,Province/State,Country/Region,Lat,Long,date,num_deaths_x,num_deaths_y
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0,0
...,...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981,5637